#!/usr/bin/env bash

set -euo pipefail

SCRIPT_NAME="$(basename "$0")"

PROFILE="balanced"
FORCE=0
DRY_RUN=0
BACKUP=0
TOOLS_CSV="gemini,qwen,windsurf,jetbrains,claude,codex,copilot"
WRITTEN_FILES=()

usage() {
  cat <<EOF
Usage: $SCRIPT_NAME [options]

Generate AI/CLI ignore and instruction files for mobile projects.

Options:
  --profile <balanced|strict>  Choose rule intensity. Default: balanced
  --tools <csv>                Tools to generate. Default: $TOOLS_CSV
  --force                      Overwrite existing non-ignore files
  --backup                     Backup files to <file>.bak before writing
  --dry-run                    Show what would be created
  -h, --help                   Show this help

Supported tools:
  gemini       -> .geminiignore
  qwen         -> .qwenignore
  windsurf     -> .codeiumignore
  jetbrains    -> .aiignore
  noai         -> .noai
  claude       -> .claude/settings.json
  codex        -> AGENTS.md
  gpt          -> alias of codex
  openai       -> alias of codex
  copilot      -> .github/copilot-instructions.md, .copilotignore
  all          -> all of the above

Examples:
  $SCRIPT_NAME
  $SCRIPT_NAME --profile strict --tools gemini,qwen,windsurf,jetbrains,codex
  $SCRIPT_NAME --tools all --dry-run
EOF
}

log() {
  printf '%s\n' "$*"
}

warn() {
  printf 'Warning: %s\n' "$*" >&2
}

die() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

contains_tool() {
  local needle="$1"
  shift
  local item
  for item in "$@"; do
    if [[ "$item" == "$needle" ]]; then
      return 0
    fi
  done
  return 1
}

normalize_tool() {
  case "$1" in
    gemini) printf 'gemini\n' ;;
    qwen) printf 'qwen\n' ;;
    windsurf|codeium) printf 'windsurf\n' ;;
    jetbrains|aiassistant|idea) printf 'jetbrains\n' ;;
    noai|jetbrains-noai) printf 'noai\n' ;;
    claude|anthropic) printf 'claude\n' ;;
    codex|gpt|openai) printf 'codex\n' ;;
    copilot|github) printf 'copilot\n' ;;
    all) printf 'all\n' ;;
    *) return 1 ;;
  esac
}

append_line() {
  local line="$1"
  if [[ -z "${BUFFER:-}" ]]; then
    BUFFER="$line"
  else
    BUFFER+=$'\n'"$line"
  fi
}

record_written_file() {
  local path="$1"

  if ! contains_tool "$path" "${WRITTEN_FILES[@]:-}"; then
    WRITTEN_FILES+=("$path")
  fi
}

build_ignore_content() {
  BUFFER=""

  append_line "# Generated by $SCRIPT_NAME"
  append_line "# Profile: $PROFILE"
  append_line "# Syntax follows .gitignore-style patterns."
  append_line ""
  append_line "# Security and secrets"
  append_line "*.jks"
  append_line "*.keystore"
  append_line "*.pem"
  append_line "*.key"
  append_line "*.p12"
  append_line "*.pfx"
  append_line ".env"
  append_line ".env.*"
  append_line "!.env.example"
  append_line "!.env.sample"
  append_line "local.properties"
  append_line "google-services.json"
  append_line "GoogleService-Info.plist"
  append_line "service-account-key.json"
  append_line "signing-key.json"
  append_line "Secrets.apple"
  append_line ""
  append_line "# Android and Gradle"
  append_line ".gradle/"
  append_line "**/build/"
  append_line "captures/"
  append_line ".externalNativeBuild/"
  append_line ".cxx/"
  append_line "*.apk"
  append_line "*.aab"
  append_line ""
  append_line "# Apple platforms"
  append_line "DerivedData/"
  append_line "*.xcuserstate"
  append_line "*.moved-aside"
  append_line "*.dSYM/"
  append_line "*.xcarchive"
  append_line "*.ipa"
  append_line ".swiftpm/"
  append_line ".build/"
  append_line ""
  append_line "# Kotlin Multiplatform"
  append_line ".kotlin/"
  append_line ".konan/"
  append_line ""
  append_line "# Coverage, logs and caches"
  append_line "coverage/"
  append_line "*.hprof"
  append_line "*.class"
  append_line "*.pyc"
  append_line "*.log"
  append_line ""
  append_line "# Generated dependency trees"
  append_line "vendor/bundle/"

  if [[ "$PROFILE" == "strict" ]]; then
    append_line "Pods/"
    append_line "node_modules/"
    append_line ".idea/"
    append_line ".vscode/"
    append_line "*.framework/"
    append_line "*.xcframework/"
    append_line "*.png"
    append_line "*.jpg"
    append_line "*.jpeg"
    append_line "*.gif"
    append_line "*.webp"
    append_line "*.mov"
    append_line "*.mp4"
    append_line "*.wav"
    append_line "*.mp3"
    append_line "*.pdf"
  else
    append_line ""
    append_line "# IDE and system noise"
    append_line ".idea/workspace.xml"
    append_line ".idea/tasks.xml"
    append_line ".idea/caches/"
    append_line ".idea/shelf/"
    append_line ".idea/httpRequests/"
    append_line ".DS_Store"
    append_line "Thumbs.db"
    append_line ""
    append_line "# Optional heavy assets"
    append_line "fastlane/screenshots/"
    append_line "fastlane/test_output/"
  fi

  printf '%s\n' "$BUFFER"
}

build_claude_settings() {
  cat <<EOF
{
  "permissions": {
    "deny": [
      "Read(./.env)",
      "Read(./.env.*)",
      "Read(./local.properties)",
      "Read(./google-services.json)",
      "Read(./GoogleService-Info.plist)",
      "Read(./service-account-key.json)",
      "Read(./signing-key.json)",
      "Read(./Secrets.apple)",
      "Read(./**/*.jks)",
      "Read(./**/*.keystore)",
      "Read(./**/*.pem)",
      "Read(./**/*.key)",
      "Read(./**/*.p12)",
      "Read(./**/*.pfx)",
      "Read(./.gradle/**)",
      "Read(./**/build/**)",
      "Read(./DerivedData/**)",
      "Read(./.konan/**)"
    ]
  }
}
EOF
}

build_agents_md() {
  cat <<EOF
# AGENTS.md

Repository instructions for coding agents such as Codex, GPT-based coding workflows, and GitHub Copilot CLI.

## Scope

- Focus on Android, iOS, and Kotlin Multiplatform source code and build logic.
- Do not read or include secrets, signing files, provisioning artifacts, or generated build outputs unless the user explicitly asks.

## Sensitive files and folders

- Treat these as off-limits by default: \`.env*\`, \`local.properties\`, \`google-services.json\`, \`GoogleService-Info.plist\`, \`*.jks\`, \`*.keystore\`, \`*.pem\`, \`*.key\`, \`*.p12\`, \`*.pfx\`.
- Avoid generated directories: \`.gradle/\`, \`**/build/\`, \`DerivedData/\`, \`.konan/\`, \`Pods/\`, \`node_modules/\`.

## Working style

- Prefer minimal, targeted changes over broad rewrites.
- Preserve existing project conventions and naming.
- When editing mobile projects, verify platform-specific side effects before changing shared code.
- If a requested change requires inspecting a sensitive file, stop and ask first.
EOF
}

build_copilot_instructions() {
  cat <<EOF
# GitHub Copilot Instructions

Treat this repository as a mobile codebase with Android, iOS, and Kotlin Multiplatform concerns.

- Prioritize source files and build configuration over generated output.
- Ignore secrets and signing artifacts unless the user explicitly requests access.
- Avoid reading or summarizing \`.env*\`, \`local.properties\`, \`google-services.json\`, \`GoogleService-Info.plist\`, and certificate or keystore files.
- Prefer small, reviewable patches and preserve existing architecture.
- Be careful with changes that affect both shared and platform-specific targets.
EOF
}

write_file() {
  local path="$1"
  local content="$2"
  local dir

  dir="$(dirname "$path")"

  if [[ "$DRY_RUN" -eq 1 ]]; then
    if [[ -e "$path" ]]; then
      log "Would update: $path"
    else
      log "Would create: $path"
    fi
    return 0
  fi

  mkdir -p "$dir"

  if [[ -e "$path" && "$FORCE" -ne 1 ]]; then
    warn "Skipping existing file: $path (use --force to overwrite)"
    return 0
  fi

  if [[ -e "$path" && "$BACKUP" -eq 1 ]]; then
    cp "$path" "$path.bak"
    log "Backed up: $path.bak"
  fi

  printf '%s\n' "$content" > "$path"
  log "Wrote: $path"
  record_written_file "$path"
}

merge_ignore_content() {
  local path="$1"
  local generated_content="$2"
  local gitignore_rules=""
  local existing_rules=""

  if [[ -f ".gitignore" ]]; then
    gitignore_rules="$(awk 'NF && $0 !~ /^[[:space:]]*#/' ".gitignore")"
  fi

  if [[ -f "$path" ]]; then
    existing_rules="$(awk 'NF && $0 !~ /^[[:space:]]*#/' "$path")"
  fi

  {
    if [[ -n "$gitignore_rules" ]]; then
      printf '# Imported rules from .gitignore\n'
      printf '%s\n' "$gitignore_rules"
      printf '\n'
    fi

    if [[ -n "$existing_rules" ]]; then
      printf '# Preserved local rules from %s\n' "$path"
      printf '%s\n' "$existing_rules"
      printf '\n'
    fi

    printf '%s\n' "$generated_content"
  } | awk '
    BEGIN { previous_blank = 1 }
    {
      if ($0 == "") {
        if (!previous_blank) {
          print ""
          previous_blank = 1
        }
        next
      }

      previous_blank = 0

      if (!seen[$0]++) {
        print $0
      }
    }
  '
}

write_ignore_file() {
  local path="$1"
  local generated_content="$2"
  local dir
  local merged_content
  local current_content=""

  dir="$(dirname "$path")"
  merged_content="$(merge_ignore_content "$path" "$generated_content")"

  if [[ -f "$path" ]]; then
    current_content="$(cat "$path")"
  fi

  if [[ "$DRY_RUN" -eq 1 ]]; then
    if [[ ! -e "$path" ]]; then
      log "Would create merged ignore file: $path"
    elif [[ "$current_content" == "$merged_content" ]]; then
      log "Would keep unchanged: $path"
    else
      log "Would merge and update: $path"
    fi
    return 0
  fi

  mkdir -p "$dir"

  if [[ -e "$path" && "$current_content" == "$merged_content" ]]; then
    log "Unchanged: $path"
    return 0
  fi

  if [[ -e "$path" && "$BACKUP" -eq 1 ]]; then
    cp "$path" "$path.bak"
    log "Backed up: $path.bak"
  fi

  printf '%s\n' "$merged_content" > "$path"
  log "Wrote merged ignore file: $path"
  record_written_file "$path"
}

prompt_global_gitignore_update() {
  local answer
  local global_gitignore
  local existing_rules=""
  local path
  local appended=0

  [[ "$DRY_RUN" -eq 0 ]] || return 0
  [[ "${#WRITTEN_FILES[@]}" -gt 0 ]] || return 0
  [[ -t 0 && -t 1 ]] || return 0

  printf 'Add generated files to the global gitignore? [y/N] '
  read -r answer || return 0

  case "$answer" in
    y|Y|yes|YES) ;;
    *) return 0 ;;
  esac

  global_gitignore="$(git config --global --get core.excludesfile || true)"
  if [[ -z "$global_gitignore" ]]; then
    global_gitignore="$HOME/.gitignore_global"
    git config --global core.excludesfile "$global_gitignore"
    log "Configured global gitignore: $global_gitignore"
  fi

  mkdir -p "$(dirname "$global_gitignore")"
  touch "$global_gitignore"
  existing_rules="$(awk 'NF && $0 !~ /^[[:space:]]*#/' "$global_gitignore")"

  for path in "${WRITTEN_FILES[@]}"; do
    if ! grep -Fqx "$path" <<< "$existing_rules"; then
      printf '%s\n' "$path" >> "$global_gitignore"
      appended=1
      log "Added to global gitignore: $path"
    fi
  done

  if [[ "$appended" -eq 0 ]]; then
    log "Global gitignore already contains all generated file rules."
  fi
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --profile)
        [[ $# -ge 2 ]] || die "--profile requires a value"
        PROFILE="$2"
        shift 2
        ;;
      --tools)
        [[ $# -ge 2 ]] || die "--tools requires a value"
        TOOLS_CSV="$2"
        shift 2
        ;;
      --force)
        FORCE=1
        shift
        ;;
      --backup)
        BACKUP=1
        shift
        ;;
      --dry-run)
        DRY_RUN=1
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        die "Unknown argument: $1"
        ;;
    esac
  done

  case "$PROFILE" in
    balanced|strict) ;;
    *) die "Invalid profile: $PROFILE" ;;
  esac
}

parse_tools() {
  local raw="$1"
  local normalized=()
  local item
  local tool

  IFS=',' read -r -a REQUESTED <<< "$raw"
  for item in "${REQUESTED[@]}"; do
    item="${item//[[:space:]]/}"
    [[ -n "$item" ]] || continue

    tool="$(normalize_tool "$item")" || die "Unsupported tool: $item"
    if [[ "$tool" == "all" ]]; then
      normalized=(gemini qwen windsurf jetbrains claude codex copilot)
      break
    fi

    if ! contains_tool "$tool" "${normalized[@]:-}"; then
      normalized+=("$tool")
    fi
  done

  [[ "${#normalized[@]}" -gt 0 ]] || die "No tools selected"
  SELECTED_TOOLS=("${normalized[@]}")
}

generate_files() {
  local ignore_content
  ignore_content="$(build_ignore_content)"

  if contains_tool "gemini" "${SELECTED_TOOLS[@]}"; then
    write_ignore_file ".geminiignore" "$ignore_content"
  fi

  if contains_tool "qwen" "${SELECTED_TOOLS[@]}"; then
    write_ignore_file ".qwenignore" "$ignore_content"
  fi

  if contains_tool "windsurf" "${SELECTED_TOOLS[@]}"; then
    write_ignore_file ".codeiumignore" "$ignore_content"
  fi

  if contains_tool "jetbrains" "${SELECTED_TOOLS[@]}"; then
    write_ignore_file ".aiignore" "$ignore_content"
  fi

  if contains_tool "noai" "${SELECTED_TOOLS[@]}"; then
    write_file ".noai" "# Remove this file if you want JetBrains AI Assistant enabled for this project."
  fi

  if contains_tool "claude" "${SELECTED_TOOLS[@]}"; then
    write_file ".claude/settings.json" "$(build_claude_settings)"
  fi

  if contains_tool "codex" "${SELECTED_TOOLS[@]}"; then
    write_file "AGENTS.md" "$(build_agents_md)"
  fi

  if contains_tool "copilot" "${SELECTED_TOOLS[@]}"; then
    write_file ".github/copilot-instructions.md" "$(build_copilot_instructions)"
    write_ignore_file ".copilotignore" "$ignore_content"
  fi
}

main() {
  parse_args "$@"
  parse_tools "$TOOLS_CSV"

  log "Generating AI/CLI project files..."
  log "Profile: $PROFILE"
  log "Tools: ${SELECTED_TOOLS[*]}"

  generate_files
  prompt_global_gitignore_update

  if [[ "$DRY_RUN" -eq 1 ]]; then
    log "Dry run complete."
  else
    log "Done."
  fi
}

main "$@"
